# Generated by Django 4.1.6 on 2023-02-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=99),
        ),
    ]
